export const quickJobsMockData = {
  updatedAtText: '2026.05.09 18:20',
  profiles: [
    {
      id: '3',
      name: '기본 프로필',
      isDefault: true,
      role: '사무행정 · 고객상담',
      disabilitySummary: '지체 · 휠체어 이동 고려',
      completionRate: 92,
      missingRequiredFields: []
    },
    {
      id: '4',
      name: '보완 중인 프로필',
      isDefault: false,
      role: '데이터 입력',
      disabilitySummary: '청각 · 문자 안내 선호',
      completionRate: 58,
      missingRequiredFields: ['희망 직무', '보유 기술/역량', '경력 정보']
    }
  ],
  selectedFilters: ['서울 강남구', '정규직', '장애인 우대', '마감 7일 이내'],
  jobs: [
    {
      id: 'quick-job-1',
      externalId: 'KEPAD-20260508-0001',
      source: {
        busplaName: '서울특별시 시설관리공단',
        jobNm: '민원 상담 및 사무지원 담당자',
        compAddr: '서울 중구 서소문로 124',
        empType: '정규직',
        enterType: '경력',
        salaryType: '월급',
        salary: '265만원',
        termDate: '20260516',
        offerregDt: '20260508',
        regDt: '20260508',
        reqCareer: '경력 1년 이상',
        reqEduc: '전문대졸 이상',
        reqMajor: '사회복지학, 행정학 우대',
        reqLicens: '컴퓨터활용능력 우대',
        geoLatitude: 37.56371,
        geoLongitude: 126.975
      },
      company: '서울특별시 시설관리공단',
      title: '민원 상담 및 사무지원 담당자',
      occupation: '상담원 · 사무보조',
      location: '서울 중구',
      employmentType: '정규직',
      salary: '월 265만원',
      salaryValue: 265,
      experience: '경력 1년 이상',
      education: '전문대졸 이상',
      major: '사회복지학, 행정학 우대',
      certificates: '컴퓨터활용능력 우대',
      deadlineDate: '2026.05.16',
      dueLabel: 'D-7',
      isDeadlineSoon: true,
      isStandardWorkplace: true,
      prefersDisabled: true,
      agency: '한국장애인고용공단 서울지사',
      contact: '박서연 과장 · 02-6320-1120',
      match: {
        score: 87,
        grade: '높음',
        reasons: ['상담 업무 경력이 공고 요구사항과 유사합니다.', '보유 문서 작성 역량이 우대사항과 일치합니다.', '경력 조건을 충족합니다.'],
        roleFit: '일치',
        skills: [
          ['문서 작성', '일치'],
          ['민원 응대', '일치'],
          ['컴퓨터활용능력', '확인 필요']
        ],
        education: '일치',
        experience: '일치',
        positive: ['상담 업무 경력이 공고 요구사항과 유사합니다.', '보유 문서 작성 역량이 우대사항과 일치합니다.', '정규직과 월급 조건이 희망 조건에 맞습니다.'],
        caution: ['컴퓨터활용능력 자격증 보유 여부는 지원 전에 확인이 필요합니다.'],
        missing: ['자격증 상세 정보']
      },
      companyInfo: {
        name: '서울특별시 시설관리공단',
        address: '서울 중구 서소문로 124',
        standardWorkplace: '해당',
        certification: '인증 유지',
        agency: '한국장애인고용공단 서울지사'
      }
    },
    {
      id: 'quick-job-2',
      externalId: 'KEPAD-20260508-0002',
      source: {
        busplaName: '브릿지서비스센터',
        jobNm: '공공기관 문서 분류 및 데이터 입력',
        compAddr: '서울 마포구 월드컵북로 21',
        empType: '계약직',
        enterType: '신입',
        salaryType: '시급',
        salary: '12,000원',
        termDate: '20260512',
        offerregDt: '20260508',
        regDt: '20260508',
        reqCareer: '무관',
        reqEduc: '고졸 이상',
        reqMajor: '무관',
        reqLicens: '무관',
        geoLatitude: 37.5563,
        geoLongitude: 126.9236
      },
      company: '브릿지서비스센터',
      title: '공공기관 문서 분류 및 데이터 입력',
      occupation: '데이터 입력원',
      location: '서울 마포구',
      employmentType: '계약직',
      salary: '시급 12,000원',
      salaryValue: 220,
      experience: '무관',
      education: '고졸 이상',
      major: '무관',
      certificates: '없음',
      deadlineDate: '2026.05.12',
      dueLabel: 'D-3',
      isDeadlineSoon: true,
      isStandardWorkplace: false,
      prefersDisabled: true,
      agency: '서울고용복지플러스센터',
      contact: '채용지원팀 · 02-707-1800',
      match: {
        score: 74,
        grade: '보통',
        reasons: ['문서 분류와 반복 입력 역량을 바로 활용할 수 있습니다.', '경력 무관 공고라 지원 장벽이 낮습니다.', '계약직 조건은 지원 전 확인이 필요합니다.'],
        roleFit: '부분 일치',
        skills: [
          ['문서 분류', '일치'],
          ['데이터 입력', '일치'],
          ['반복 업무 집중도', '확인 필요']
        ],
        education: '일치',
        experience: '일치',
        positive: ['문서 분류와 반복 입력 역량을 바로 활용할 수 있습니다.', '경력 무관 공고라 지원 장벽이 낮습니다.', '장애인 우대 공고입니다.'],
        caution: ['고용형태가 계약직이므로 계약기간과 전환 가능성을 확인해보세요.'],
        missing: ['반복 업무 선호도']
      },
      companyInfo: {
        name: '브릿지서비스센터',
        address: '서울 마포구 월드컵북로 21',
        standardWorkplace: '해당 없음',
        certification: '확인 필요',
        agency: '서울고용복지플러스센터'
      }
    },
    {
      id: 'quick-job-3',
      externalId: 'KEPAD-20260508-0003',
      source: {
        busplaName: '한강복지재단',
        jobNm: '복지 행정 보조 및 전화 안내',
        compAddr: '서울 영등포구 국회대로 596',
        empType: '시간제',
        enterType: '신입',
        salaryType: '월급',
        salary: '180만원',
        termDate: '20260523',
        offerregDt: '20260508',
        regDt: '20260508',
        reqCareer: '신입 가능',
        reqEduc: '학력 무관',
        reqMajor: '사회복지 관련 전공 우대',
        reqLicens: '사회복지사 우대',
        geoLatitude: 37.5263,
        geoLongitude: 126.9029
      },
      company: '한강복지재단',
      title: '복지 행정 보조 및 전화 안내',
      occupation: '행정 사무원',
      location: '서울 영등포구',
      employmentType: '시간제',
      salary: '월 180만원',
      salaryValue: 180,
      experience: '신입 가능',
      education: '학력 무관',
      major: '사회복지 관련 전공 우대',
      certificates: '사회복지사 우대',
      deadlineDate: '2026.05.23',
      dueLabel: 'D-14',
      isDeadlineSoon: false,
      isStandardWorkplace: true,
      prefersDisabled: false,
      agency: '영등포구 일자리센터',
      contact: '김도윤 상담사 · 02-2670-4100',
      match: {
        score: null,
        grade: '확인 필요',
        reasons: ['문서 정리 업무는 보유 역량과 맞습니다.', '전화 안내 업무 가능 여부 확인이 필요합니다.', '전공 및 자격증 정보가 부족합니다.'],
        roleFit: '확인 필요',
        skills: [
          ['문서 정리', '일치'],
          ['전화 안내', '확인 필요'],
          ['사회복지 지식', '확인 필요']
        ],
        education: '일치',
        experience: '일치',
        positive: ['신입 지원이 가능합니다.'],
        caution: ['전화 안내 업무 비중이 있어 상세 업무 확인이 필요합니다.'],
        missing: ['전공 정보', '자격증 정보', '전화 안내 가능 여부']
      },
      companyInfo: {
        name: '한강복지재단',
        address: '서울 영등포구 국회대로 596',
        standardWorkplace: '해당',
        certification: '인증 유지',
        agency: '영등포구 일자리센터'
      }
    }
  ]
};
